### PR TITLE
add new picture, fixed existing ones

### PR DESCRIPTION
**Pull request by genti94**
Left out customisation section.

left out the todo --> .. todo:: an image to show file in the OS X Finder and in a text editor
because I work this week on a pc. Will be fixed on monday. Same applies to the draft button fix. Uses different font and size on pc. Will be fixed also on monday.

### CODE REVIEW

**Comment by FinalAngel** [comment]
@genti94 whats the status here?

**Comment by evildmp** [comment]
Hi @genti94.

A few issues here that need to be addressed before these changes can be merged.

* the new files use ``.PNG`` instead of ``.png``; we need to be consistent
* please use ``alt`` text that follows the example in the existing documentation, such as in https://github.com/aldryn/aldryn-docs/raw/master/docs/tutorial/basic-content-editing.rst (so use ``The 'Manage Addons' menu`` (note single quotes), not ``manage addons``
* don't forget to use the ``align`` and ``width`` attributes (see the existing pages in the tutorial for examples) for images that don't need to take up the whole width of the page

Let me know if you need any help or have any questions.

**Comment by evildmp** [comment]
@genti94 please merge aldryn:master into your genti94:genti-changes branch before continuing to ensure you have latest changes.

**Comment by evildmp** [comment]
OK, we're getting there.

I will merge these changes with some corrections, and then send you the commit as a pull request so you can see what I have changed, plus further instructions for the next round!

**Comment by evildmp** [comment]
@genti94 please don't forget https://github.com/genti94/aldryn-docs/pull/1, where I would like you to merge the upstream progress into your branch before making some corrections and sending a new pull request upstream.

**Pull request merged**
